
package com.epam.cdp.jee.todo.soap.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TaskWebService", targetNamespace = "http://soap.todo.jee.cdp.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TaskWebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.epam.cdp.jee.todo.soap.client.Task>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tasks", targetNamespace = "http://soap.todo.jee.cdp.epam.com/", className = "com.epam.cdp.jee.todo.soap.client.Tasks")
    @ResponseWrapper(localName = "tasksResponse", targetNamespace = "http://soap.todo.jee.cdp.epam.com/", className = "com.epam.cdp.jee.todo.soap.client.TasksResponse")
    public List<Task> tasks();

}
