
package com.epam.cdp.jee.todo.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TaskWebServiceService", targetNamespace = "http://soap.todo.jee.cdp.epam.com/", wsdlLocation = "file:/vagrant/JEEEssentials/todo/src/main/resources/META-INF/wsdl/TaskWebService.wsdl")
public class TaskWebServiceService
    extends Service
{

    private final static URL TASKWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TASKWEBSERVICESERVICE_EXCEPTION;
    private final static QName TASKWEBSERVICESERVICE_QNAME = new QName("http://soap.todo.jee.cdp.epam.com/", "TaskWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/vagrant/JEEEssentials/todo/src/main/resources/META-INF/wsdl/TaskWebService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TASKWEBSERVICESERVICE_WSDL_LOCATION = url;
        TASKWEBSERVICESERVICE_EXCEPTION = e;
    }

    public TaskWebServiceService() {
        super(__getWsdlLocation(), TASKWEBSERVICESERVICE_QNAME);
    }

    public TaskWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TASKWEBSERVICESERVICE_QNAME, features);
    }

    public TaskWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, TASKWEBSERVICESERVICE_QNAME);
    }

    public TaskWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TASKWEBSERVICESERVICE_QNAME, features);
    }

    public TaskWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TaskWebService
     */
    @WebEndpoint(name = "TaskWebServicePort")
    public TaskWebService getTaskWebServicePort() {
        return super.getPort(new QName("http://soap.todo.jee.cdp.epam.com/", "TaskWebServicePort"), TaskWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskWebService
     */
    @WebEndpoint(name = "TaskWebServicePort")
    public TaskWebService getTaskWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.todo.jee.cdp.epam.com/", "TaskWebServicePort"), TaskWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TASKWEBSERVICESERVICE_EXCEPTION!= null) {
            throw TASKWEBSERVICESERVICE_EXCEPTION;
        }
        return TASKWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
